name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  run:
    name: Run
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up V version latest
      uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: master
      id: v

    - name: Verify fmt
      run: v fmt -verify .

    - name: Run SQL tests
      run: v -stats -prod test vsql

    - name: Run examples
      run: for f in `ls examples/*.v`; do v -prod run $f; done

    - name: Build macOS binaries
      run: |
        v -prod cmd/vsql.v
        zip -j vsql-macos.zip cmd/vsql

    # See https://github.com/vlang/v/issues/10992
    #- name: Build linux binaries
    #  run: |
    #    v -os linux -prod cmd/vsql.v
    #    zip -j vsql-linux.zip cmd/vsql

    # Cross compiling for windows takes a long time because mingw-w64 has to be
    # installed. So we only run this when we're doing a release.
    - name: Build windows binaries
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        brew install mingw-w64
        v -os windows -prod cmd/vsql.v
        zip -j vsql-windows.zip cmd/vsql.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          vsql-macos.zip
          vsql-windows.zip
