name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  run:
    name: Run
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up V version latest
      uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: master
      id: v

    - name: Verify fmt
      run: make fmt-verify

    - name: Run SQL tests
      run: make test

    - name: Run examples
      run: make examples

    - name: Set version
      if: startsWith(github.ref, 'refs/tags/')
      run: sed -i -e "s/MISSING_VERSION/${GITHUB_REF##*/} `date +'%F'`/g" cmd/vsql.v

    - name: Build macOS binaries
      run: |
        make vsql
        zip -j vsql-macos.zip cmd/vsql

    # See https://github.com/vlang/v/issues/10992
    #- name: Build linux binaries
    #  run: |
    #    v -os linux -prod cmd/vsql.v
    #    zip -j vsql-linux.zip cmd/vsql

    # Cross compiling for windows takes a long time because mingw-w64 has to be
    # installed. It would be nice to skip this, but until we have code that
    # specific to each OS we need to keep this in place.
    - name: Build windows binaries
      run: |
        brew install mingw-w64
        v -os windows -prod cmd/vsql.v
        zip -j vsql-windows.zip cmd/vsql.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          vsql-macos.zip
          vsql-windows.zip
